name: essential_xlsx
description: A library for create Excel XLSX file
version: 1.0.0

homepage: https://github.com/insinfo/essential_xlsx
authors: 
  - Isaque Neves <insinfo2008@gmail.com>  

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies: 
  #intl: ^0.15.8
  xml: '>=3.7.0 <4.0.0'
  archive: '>=2.0.13 <3.0.0'

dev_dependencies:  
  build_runner: any
  build_test: any
  build_web_compilers: any
  pedantic: ^1.7.0
  test: ^1.6.0
